#encoding: utf-8
class FillBrands < ActiveRecord::Migration
  
  def up
    ["INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(3, 'PIONEER', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(4, 'STANTON', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(52, 'DENON', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(115, 'ELECTRO-HARMONIX', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(7, 'VESTAX', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(8, 'TECHNICS', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(9, 'UDG', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(11, 'M-AUDIO', false);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(12, 'IBANEZ', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(15, 'YAMAHA', false);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(16, 'KORG', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(113, 'DUNLOP', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(19, 'ZOOM', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(21, 'JACKSON', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(119, 'GROOVE TUBES', false);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(23, 'MARSHALL', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(25, 'KURZWEIL', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(114, 'KUSTOM', false);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(111, 'APHEX SYSTEMS', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(112, 'ART', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(31, 'JBL PRO', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(170, 'RODE', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(34, 'ANTARI', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(35, 'BIG DIPPER', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(36, 'CR LASER', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(37, 'SENNHEISER', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(38, 'AKG', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(39, 'SOUNDCRAFT', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(40, 'DBX', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(41, 'TONYLEE', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(109, 'GEMINI', false);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(44, 'YONGFA', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(45, 'RADIUM', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(46, 'LIGHT SKY', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(47, 'PHD', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(169, 'HUGHES AND KETTNER', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(49, 'LEXICON', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(50, 'ORTOFON', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(51, 'SANYO', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(53, 'MACKIE', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(54, 'FENDER', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(55, 'GIBSON', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(56, 'FENDER SQUIER', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(116, 'SONY', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(58, 'NOVATION', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(59, 'PRESONUS', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(60, 'ECHO', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(61, 'DIGIDESIGN', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(62, 'AARDVARK', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(63, 'ICON', false);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(64, 'MIDITECH', false);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(65, 'ALESIS', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(66, 'FOSTEX ', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(67, 'TAPCO BY MACKIE', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(68, 'DIGITECH', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(69, 'VOX', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(70, 'T.C.ELECTRONIC', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(71, 'MAXIMUM ACOUSTICS', false);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(72, 'ALLEN AND HEATH', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(74, 'NATIVE INSTRUMENTS', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(75, 'KRK', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(76, 'AKAI PROFESSIONAL', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(117, 'ARION', false);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(79, 'ЗЕРКАЛЬНЫЙ ШАР', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(80, 'ЗЕРКАЛЬНАЯ ПОЛУСФЕРА', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(81, 'ЗЕРКАЛЬНЫЙ КУБ', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(82, 'EVOLUTION', false);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(83, 'RELOOP', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(84, 'APOGEE', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(85, 'FOCUSRITE', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(86, 'MOTU', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(87, 'AIRSHOW', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(88, 'JEM', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(89, 'ACME', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(90, 'PSL', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(91, 'ADAM', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(92, 'INFRASONIC', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(93, 'GENELEC', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(94, 'JOEMEEK', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(95, 'ALVAREZ', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(96, 'STUDIO PROJECT', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(97, 'AMPEG', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(98, 'SM PRO AUDIO', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(99, 'ARIA', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(101, 'BSS', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(102, 'CROWN', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(103, 'STEINBERG', false);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(104, 'SAMSON', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(105, 'NEUMANN', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(106, 'BEYERDYNAMIC', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(107, 'I-KEY', false);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(108, 'ESI', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(120, 'MORLEY', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(121, 'CRATE', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(122, 'RANDALL', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(123, 'PARKER', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(124, 'HIWATT', false);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(125, 'GIG-FX', false);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(126, 'WASHBURN', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(127, 'NUX', false);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(128, 'PEAVEY', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(129, 'MESA BOOGIE', false);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(130, 'SWR', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(131, 'LAG', false);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(132, 'FERNANDES', false);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(133, 'BURNY', false);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(134, 'EDEN', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(135, 'HALO', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(136, 'DASLIGHT', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(137, 'MXL', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(160, 'CLAVIA', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(152, 'RADIAL', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(154, 'DIMARZIO', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(155, 'MAGMA', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(156, 'MIPRO', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(157, 'KONIG and MEYER', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(158, 'DYNAUDIO', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(159, 'AUDIX', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(161, 'STUDIOLOGIC', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(162, 'DPA MICROPHONES', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(163, 'AMERICAN AUDIO', false);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(164, 'META', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(165, 'TASCAM ', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(166, 'JTS', false);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(167, 'E-MU CREATIVE', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(168, 'BLUE MICROPHONES', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(171, 'ALTO', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(172, 'RME', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(173, 'AUDIO TECHNICA', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(174, 'PHONIC', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(175, 'SINN7', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(177, 'AVID', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(176, 'GERMAN MAESTRO (MB QUART)', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(178, 'ATHLETIC', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(179, 'EPIPHONE ', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(180, 'JAY TURSER', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(181, 'MBN', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(182, 'HKAUDIO', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(183, 'QSC', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(184, 'CHARVEL ', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(185, 'TAKAMINE', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(186, 'ORANGE', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(187, 'LAKLAND', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(188, 'T-REX', true);",
    "INSERT INTO `brands` (`id`, `name`, `visibility`) VALUES(189, 'CORDIAL', true);"].each do |line|
      execute line
    end
  end
  
  def down
  end
  
end