#encoding: utf-8
class FillSubcategories < ActiveRecord::Migration
  
  def up
    ["INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(1, 1, 'DJ-комплекты', 'DJ-комплекты', true, 1);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(2, 1, 'СD/DVD проигрыватели', 'СD/DVD проигрыватели', true, 2);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(3, 1, 'Микшерные пульты ', 'Микшерные пульты ', true, 3);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(4, 3, 'Звуковые карты, Интерфейсы', 'Звуковые карты, Интерфейсы', true, 1);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(5, 5, 'Уцененное оборудование ', 'Уцененное оборудование ', true, 1);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(6, 6, 'Спрос', 'Спрос', true, 1);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(7, 2, 'Гитары', 'Гитары', true, 1);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(8, 2, 'Комбо усилители', 'Комбо усилители', true, 2);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(9, 4, 'Световое оборудование', 'Световое оборудование', true, 1);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(10, 4, 'Звуковое оборудование', 'Звуковое оборудование', true, 2);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(11, 1, 'Контроллеры', 'Контроллеры', false, 4);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(12, 1, 'Вертушки', 'Вертушки', false, 5);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(13, 1, 'Эффекторы', 'Эффекторы', false, 6);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(14, 1, 'Прочее', 'Прочее', true, 7);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(15, 2, 'Эффекты', 'Эффекты', true, 3);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(16, 2, 'Клавишные', 'Клавишные', true, 4);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(17, 2, 'Ударные', 'Ударные', true, 5);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(18, 2, 'Прочее', 'Прочее', true, 7);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(19, 4, 'Микрофоны', 'Микрофоны', true, 3);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(20, 4, 'Спецэффекты и лазера', 'Спецэффекты и лазера', true, 4);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(21, 4, 'Мультимедия', 'Мультимедия', false, 5);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(22, 4, 'Прочее', 'Прочее', false, 6);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(24, 24, 'СD/DVD проигрыватели', 'СD/DVD проигрыватели', true, 2);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(25, 24, 'Микшерные пульты', 'Микшерные пульты', true, 3);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(26, 24, 'DJ Контроллеры', 'DJ Контроллеры', true, 1);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(27, 24, 'Вертушки', 'Вертушки', true, 5);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(28, 24, 'DJ Эффекторы', 'DJ Эффекторы', true, 7);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(29, 24, 'CD/Vinyl с таймкодом', 'CD/Vinyl с таймкодом', true, 11);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(30, 25, 'Акустические гитары', 'Акустические гитары', true, 2);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(32, 25, 'Усилители для электрогитар', 'Усилители для электрогитар', true, 4);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(33, 40, 'Синтезаторы', 'Синтезаторы', true, 1);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(34, 41, 'Перкусии', 'Перкусии', true, 11);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(35, 25, 'Прочее', 'Прочее', true, 12);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(146, 27, 'Головы Spot', 'Головы Spot', true, 1);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(118, 47, 'Рэковые кейсы', 'Рэковые кейсы', true, 29);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(38, 48, 'Радио микрофоны ручные', 'Радио микрофоны ручные', true, 2);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(39, 45, 'Генераторы дыма', 'Генераторы дыма', true, 2);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(55, 39, 'Проекторы', 'Проекторы', true, 0);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(43, 26, 'Звуковые карты USB', 'Звуковые карты USB', true, 1);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(47, 2, 'Комплекты', 'Комплекты', true, 6);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(48, 45, 'Лазера', 'Лазера', true, 1);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(49, 24, 'DJ наушники', 'DJ наушники', true, 7);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(50, 44, 'Микшерные   пульты ', 'Микшерные   пульты ', true, 7);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(51, 27, 'Расходные материалы/Лампы', 'Расходные материалы/Лампы', true, 22);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(53, 26, 'Наушники для студий и мониторинга', 'Наушники для студий и мониторинга', true, 5);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(54, 24, 'Иглы и картриджи ', 'Иглы и картриджи ', true, 7);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(56, 25, 'Электрогитары', 'Электрогитары', true, 1);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(57, 25, 'Бас-гитары', 'Бас-гитары', true, 3);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(58, 25, 'Усилители для бас-гитар', 'Усилители для бас-гитар', true, 5);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(59, 25, 'Усилители для  акустических гитар', 'Усилители для  акустических гитар', true, 6);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(60, 25, 'Гитарные процессоры ', 'Гитарные процессоры ', true, 7);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(61, 25, 'Педали эффектов для электрогитар', 'Педали эффектов для электрогитар', true, 8);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(62, 25, 'Педали эффектов для бас-гитар', 'Педали эффектов для бас-гитар', true, 9);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(63, 26, 'MIDI Контроллеры', 'MIDI Контроллеры', true, 4);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(64, 26, 'Студийные мониторы', 'Студийные мониторы', true, 7);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(67, 26, 'MIDI Клавиатуры', 'MIDI Клавиатуры', true, 5);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(66, 26, 'Сэмплеры,Drum-машины', 'Сэмплеры,Drum-машины', true, 10);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(68, 40, 'Рабочие станции', 'Рабочие станции', true, 2);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(69, 41, 'Ударные установки', 'Ударные установки', true, 0);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(95, 47, 'Сумки для ноутбуков и контроллеров', 'Сумки для ноутбуков и контроллеров', true, 1);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(71, 40, 'Стойки', 'Стойки', true, 5);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(72, 26, 'Звуковые карты FireWire', 'Звуковые карты FireWire', true, 2);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(73, 26, 'Звуковые карты (слотовые)', 'Звуковые карты (слотовые)', true, 3);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(76, 45, 'Зеркальные шары', 'Зеркальные шары', true, 9);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(75, 26, 'Рекордеры,Системы записи', 'Рекордеры,Системы записи', true, 12);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(77, 45, 'Зеркальные полусферы', 'Зеркальные полусферы', true, 10);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(78, 45, 'Генераторы низкого дыма', 'Генераторы низкого дыма', true, 4);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(79, 45, 'Генераторы тумана', 'Генераторы тумана', true, 6);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(80, 45, 'Генераторы мыльных пузырей', 'Генераторы мыльных пузырей', true, 2);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(81, 45, 'Генераторы снега', 'Генераторы снега', true, 3);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(82, 45, 'Генераторы пены', 'Генераторы пены', true, 5);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(83, 45, 'Зеркальные кубы', 'Зеркальные кубы', true, 11);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(84, 26, 'MIDI интерфейсы', 'MIDI интерфейсы', true, 13);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(85, 24, 'Прочее,Кроссфейдеры', 'Прочее,Кроссфейдеры', true, 13);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(86, 40, 'Цифровые пианино', 'Цифровые пианино', true, 3);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(87, 24, 'Аксессуары,Слимпматы', 'Аксессуары,Слимпматы', true, 12);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(88, 46, 'Оптический кабель', 'Оптический кабель', false, 10);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(89, 46, 'Микрофонный кабель', 'Микрофонный кабель', true, 15);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(90, 46, 'Кабеля мультикор', 'Кабеля мультикор', true, 20);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(91, 48, 'Микрофоны студия/запись', 'Микрофоны студия/запись', true, 10);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(92, 44, 'Конверторы и предусилители', 'Конверторы и предусилители', true, 16);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(94, 45, 'Жидкости,Расходные материалы ', 'Жидкости,Расходные материалы ', true, 8);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(96, 47, 'Сумки,кофры для клавишных', 'Сумки,кофры для клавишных', true, 10);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(97, 26, 'Прочее', 'Прочее', true, 18);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(98, 44, 'Компреcсоры, лимитеры, гейты', 'Компреcсоры, лимитеры, гейты', true, 8);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(99, 44, 'Процессоры эффектов', 'Процессоры эффектов', true, 9);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(100, 48, 'Аксессуары для микрофонов', 'Аксессуары для микрофонов', true, 16);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(101, 47, 'Чехлы, кофры для гитар', 'Чехлы, кофры для гитар', true, 11);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(102, 25, 'Электроакустические гитары', 'Электроакустические гитары', true, 0);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(104, 46, 'DI-box', 'DI-box', true, 1);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(105, 46, 'Патч-беи', 'Патч-беи', true, 3);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(106, 46, 'Сплиттеры', 'Сплиттеры', true, 0);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(107, 46, 'Разветвители-усилители для наушников', 'Разветвители-усилители для наушников', true, 2);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(108, 46, 'Тестеры ', 'Тестеры ', true, 30);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(110, 44, 'Усилители мощности ', 'Усилители мощности ', true, 4);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(111, 44, 'Активные акустические системы ', 'Активные акустические системы ', true, 1);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(112, 44, 'Пассивные акустические системы', 'Пассивные акустические системы', true, 2);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(113, 44, 'Эквалайзеры, кроссоверы ', 'Эквалайзеры, кроссоверы ', true, 6);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(114, 44, 'Элементы линейных массивов', 'Элементы линейных массивов', false, 3);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(115, 44, 'Звуковые процессоры', 'Звуковые процессоры', true, 5);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(116, 44, 'Зональные процессоры,микшеры ', 'Зональные процессоры,микшеры ', true, 31);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(117, 44, 'Прочее ', 'Прочее ', true, 33);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(119, 26, 'Студийные усилители', 'Студийные усилители', true, 16);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(120, 44, 'Голосовые мониторы ', 'Голосовые мониторы ', true, 4);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(121, 48, 'Театральные, радио, ТВ микрофоны', 'Театральные, радио, ТВ микрофоны', true, 14);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(122, 48, 'Инструментальные микрофоны', 'Инструментальные микрофоны', true, 4);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(123, 48, 'Фантомное питание', 'Фантомное питание', true, 17);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(124, 48, 'Микрофонные стойки', 'Микрофонные стойки', true, 20);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(125, 48, 'Шнуровые микрофоны', 'Шнуровые микрофоны', true, 1);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(126, 48, 'Микрофоны hands-free', 'Микрофоны hands-free', true, 3);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(127, 48, 'Приёмники и базы', 'Приёмники и базы', true, 18);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(128, 47, 'Рэковые стойки', 'Рэковые стойки', true, 30);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(129, 41, 'Электронные барабаны', 'Электронные барабаны', true, 30);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(130, 48, 'Конференционные микрофоны', 'Конференционные микрофоны', true, 15);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(131, 48, 'Беспроводные системы In-Ear мониторинга', 'Беспроводные системы In-Ear мониторинга', true, 19);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(132, 47, 'Сумки для пластинок', 'Сумки для пластинок', true, 2);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(133, 47, 'Сумки для оборудования', 'Сумки для оборудования', true, 9);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(134, 44, 'Голосовые процессоры, педали', 'Голосовые процессоры, педали', true, 5);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(135, 24, 'DJ комплекты', 'DJ комплекты', false, 6);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(136, 46, 'Питание, сеть', 'Питание, сеть', true, 29);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(137, 49, 'Тюнеры', 'Тюнеры', true, 1);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(138, 49, 'Гитарные стойки', 'Гитарные стойки', true, 10);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(139, 49, 'Струны для электрогитар', 'Струны для электрогитар', true, 2);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(140, 49, 'Струны для бас-гитар', 'Струны для бас-гитар', true, 3);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(141, 49, 'Струны для акустических гитар', 'Струны для акустических гитар', true, 4);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(142, 49, 'Каподастеры', 'Каподастеры', true, 5);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(143, 40, 'Усилители для клавишных ', 'Усилители для клавишных ', true, 6);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(144, 44, 'Звуковые комплекты', 'Звуковые комплекты', true, 0);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(145, 49, 'Звукосниматели', 'Звукосниматели', true, 6);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(147, 27, 'Прочее', 'Прочее', false, 40);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(148, 27, 'Сканера', 'Сканера', true, 2);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(149, 27, 'Прожекторы,PAR', 'Прожекторы,PAR', true, 3);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(153, 27, 'Колорченжеры,LED прожектора', 'Колорченжеры,LED прожектора', true, 6);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(150, 27, 'Стробоскопы, Ультрафиолет ', 'Стробоскопы, Ультрафиолет ', true, 5);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(164, 27, 'Световые эффекты', 'Световые эффекты', true, 4);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(151, 27, 'Световые декорации ', 'Световые декорации ', true, 19);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(152, 27, 'Следящие прожекторы', 'Следящие прожекторы', true, 18);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(154, 27, 'Диммеры', 'Диммеры', false, 15);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(155, 27, 'Пульты управления', 'Пульты управления', true, 16);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(156, 27, 'DMX контроллеры', 'DMX контроллеры', true, 17);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(157, 27, 'Головы Wash', 'Головы Wash', true, 1);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(158, 48, 'Прочее', 'Прочее', true, 21);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(163, 26, 'Наушники с головным микрофоном', 'Наушники с головным микрофоном', true, 6);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(160, 45, 'Аксессуары для генераторов', 'Аксессуары для генераторов', true, 7);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(161, 49, 'Гитарные ремни', 'Гитарные ремни', true, 12);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(162, 46, 'Кабеля гитарные', 'Кабеля гитарные', true, 21);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(165, 27, 'Стойки для света/Аксессуары', 'Стойки для света/Аксессуары', true, 30);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(166, 46, 'Свичеры', 'Свичеры', true, 28);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(167, 48, 'Сменные капсюли', 'Сменные капсюли', true, 19);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(168, 40, 'Прочее', 'Прочее', true, 10);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(169, 47, 'Стойки для микщеров и усилителей', 'Стойки для микщеров и усилителей', true, 31);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(170, 40, 'Тон генераторы', 'Тон генераторы', true, 4);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(171, 49, 'Средства для ухода ', 'Средства для ухода ', true, 7);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(172, 27, 'Зенитные прожектора', 'Зенитные прожектора', true, 20);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(173, 26, 'Аксессуары для мониторов', 'Аксессуары для мониторов', true, 8);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(174, 47, 'Сумки/папки для CD', 'Сумки/папки для CD', true, 3);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(175, 47, 'Подставки для ноутбуков/интерфейсов', 'Подставки для ноутбуков/интерфейсов', true, 4);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(176, 50, 'Наушники для аудиофилов', 'Наушники для аудиофилов', true, 1);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(177, 50, 'Наушники с шумоподовлением', 'Наушники с шумоподовлением', true, 17);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(178, 50, 'Беспроводные наушники ', 'Беспроводные наушники ', true, 16);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(179, 50, 'Гарнитуры', 'Гарнитуры', false, 15);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(180, 50, 'Наушники вкладыши', 'Наушники вкладыши', true, 2);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(181, 50, 'Наушники для плеера и дома', 'Наушники для плеера и дома', true, 3);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(182, 50, 'Аксессуары', 'Аксессуары', true, 18);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(183, 25, 'Лампы для усилителей', 'Лампы для усилителей', true, 11);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(184, 44, 'Активные микшерные пульты', 'Активные микшерные пульты', true, 7);",
    "INSERT INTO `subcategories` (`id`, `category_id`, `name`, `title`, `visibility`, `priority`) VALUES(185, 47, 'Стойки для акустики', 'Стойки для акустики', true, 32);"].each do |line|
      execute line
    end
  end
  
  def down
  end
  
end